# NUMPY ARRAY

In [1]:
import numpy as np

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [2]:
#creatr a 1D array
np.array([1,2,3,4])
np.array((10,20,30,40))
np.array(range(1,20))

array([1, 2, 3, 4])

array([10, 20, 30, 40])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [3]:
print(np.array([1,2,3,4]))
print(np.array((10,20,30)))
print(np.array(range(0,10)))

[1 2 3 4]
[10 20 30]
[0 1 2 3 4 5 6 7 8 9]


In [4]:
x = np.array(range(0,10))
print(x, x.shape,sep = '\n')
y = np.array([10,20,30])
print(y, y.shape,sep = '\n')

print('*'*40)

# creating 2D array
array2d = np.array([[1,2,3,4,5]])
print(array2d)
array3d = np.array([[[10,20,30,],[100,200,300],[1000,2000,3000]]])
print(array3d,array3d.shape,sep = '\n')

[0 1 2 3 4 5 6 7 8 9]
(10,)
[10 20 30]
(3,)
****************************************
[[1 2 3 4 5]]
[[[  10   20   30]
  [ 100  200  300]
  [1000 2000 3000]]]
(1, 3, 3)


In [5]:
np.array([[[10,20,30,40]]])
print(np.array([[[10,20,30,40]]]).shape)
np.array([10,20,40,50])
np.array([10,20,40,50]).shape
np.array([[2,3,4,6,7]])
np.array([[2,3,4,6,7]]).shape

array([[[10, 20, 30, 40]]])

(1, 1, 4)


array([10, 20, 40, 50])

(4,)

array([[2, 3, 4, 6, 7]])

(1, 5)

## Numpy array properties

In [6]:
#array.shape= a tuple that specifies the number of elements for eachdiamension of the array.
#array.ndim = determines the no.of diamension of an array.
#array.dtype = every ndarray has as associated data type (dtype) object from the numpy
#array.size = the total numbers elements in the array.
#array.nbytes = number of bytes used to store the data. 

In [7]:
len(array3d) # len returns the length of the first diamenssion to be the compatible with python lists
type(array3d) # python type

1

numpy.ndarray

## NumPy Arrays v/s List

**Similarity between list and array**
* Both are used for storing data.
* Both are mutable.
* Both can be indexed and iterated through.
* Both ca be sliced.

**Differences:**

In [8]:
# Python Lists are an ordered sequence of heterogeneous elements.

bag = [1,'sumit',True,18.4]
print(bag)
print(bag[1])
print(type(bag))

[1, 'sumit', True, 18.4]
sumit
<class 'list'>


In [9]:
# In numpy, the array must contain data of same type (homogeneous).

arr3d = np.array([(2,3,4,5),(2,4,5,6)])
print(arr3d,arr3d.shape, sep='\n')
print(arr3d.dtype)

[[2 3 4 5]
 [2 4 5 6]]
(2, 4)
int32


In [10]:
arr2 = np.array([(2,4.4,6),(3,4,7)])
print(arr2,arr2.shape,sep = '\n')
print(arr2.dtype)

[[2.  4.4 6. ]
 [3.  4.  7. ]]
(2, 3)
float64


In [11]:
arr4 = np.array([(1,3,5,7),(2,4,6,'4')])
print(arr4,arr4.shape,arr4.dtype,sep='\n')

[['1' '3' '5' '7']
 ['2' '4' '6' '4']]
(2, 4)
<U11


In [12]:
y = [3,4,6,7,3]
print(y)

[3, 4, 6, 7, 3]


In [13]:
#y**2

In [14]:
y = np.array([3,4,6,7,3])
print(y)
print(y**2)

[3 4 6 7 3]
[ 9 16 36 49  9]


### Reshape an array

In [15]:
array2 = np.array(range(0,10))
print(array2)
print("shape of the array:",array2.shape)
print('-'*30)
arra3 = np.array (range(2,4))
print(arra3)
print('shape of the array:',arra3.shape)
print("*"*30)
arra = np.array(range(4,2))
print(arra)

[0 1 2 3 4 5 6 7 8 9]
shape of the array: (10,)
------------------------------
[2 3]
shape of the array: (2,)
******************************
[]


In [16]:
array3 = np.array(range(0,10))
print(array3)
print("shape of the array:",array3.shape)
print("*"*30)

arra1 = array3.reshape(2,5)
print(arra1)
print('.'*30)
arra1 = array3.reshape(5,2)
print(arra1)
print('='*30)
arra1 = array3.reshape(1,2,5)
print(arra1)

[0 1 2 3 4 5 6 7 8 9]
shape of the array: (10,)
******************************
[[0 1 2 3 4]
 [5 6 7 8 9]]
..............................
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[[0 1 2 3 4]
  [5 6 7 8 9]]]


In [17]:
# Create a 3D array with 24 values starting from 100

np.array(range(100,124)).reshape(4,2,3)
np.array(range(100,124)).reshape(1,1,24)

array([[[100, 101, 102],
        [103, 104, 105]],

       [[106, 107, 108],
        [109, 110, 111]],

       [[112, 113, 114],
        [115, 116, 117]],

       [[118, 119, 120],
        [121, 122, 123]]])

array([[[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
         112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123]]])

In [18]:
type1 = np.array([1,2,4,5,6])
type2 = np.array([1.2,3.4,2.4,3])

print(type1,type1.dtype,type1.nbytes)
print(type2,type2.dtype,type2.nbytes)

[1 2 4 5 6] int32 20
[1.2 3.4 2.4 3. ] float64 32


In [19]:
type3 = np.array(['w','r','y','s'])
type4 = np.array(['sumit','sugat','rohit','abhi'])

print(type3, type3.dtype)
print(type4,type4.dtype,type4.nbytes)

['w' 'r' 'y' 's'] <U1
['sumit' 'sugat' 'rohit' 'abhi'] <U5 80


## Special NumPy functions for generating arrays

* From list: np.array
* Numerical ranges: np.arange, np.linspace…
* Homogeneous data: np.zeros, np.ones …
* Random numbers: np.random.rand, np.random.randint…

### 1 array with arange()

> The arange() function creates an array with evenly spaced values between the specified start, end, and increment values.

**syntax:**

np.arange(start,end,increment)

In [20]:
arr = np.arange(5)
print(arr)
# same as
print(np.array(range(5)))
print('-'*30)
array2 = np.arange(0,10,1).reshape(2,5)
print(array2)
print("-"*30)
arra = np.arange(9).reshape(3,3)
print(arra)

[0 1 2 3 4]
[0 1 2 3 4]
------------------------------
[[0 1 2 3 4]
 [5 6 7 8 9]]
------------------------------
[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 2. Arrays with linspace()

> The linspace() function generates an array with evenly spaced values between specified start and end values, using a specified number of elements.

**Syntax:**

np.linspace(Start, End, Number of elements)

In [21]:
arrr3 = np.linspace(10,13,4)
print(arrr3)
print('*'*20)
arry2 = (np.linspace(10,14,8))
print(arry2)
print('-'*20)
ar = np.linspace(10,21,12).reshape(4,3)
print(ar)

[10. 11. 12. 13.]
********************
[10.         10.57142857 11.14285714 11.71428571 12.28571429 12.85714286
 13.42857143 14.        ]
--------------------
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]
 [19. 20. 21.]]


### 3. Zero Array& ones  
> The zeros() function, generates an array with the specified dimensions and data type that is filled with zeros.

In [22]:
arr = np.zeros(3)
print(arr)
print('-'*30)
arr1 = np.zeros((2,6))
print(arr1)
print('-'*30)
arr2 = np.zeros((2,4,6))
print(arr2)
print('-'*30)
arra = np.ones(4)
print(arra)
print('-'*30)
arra3 = np.ones((2,4))
print(arra3)
print('-'*30)
arr = np.ones((2,3,6))
print(arr)

[0. 0. 0.]
------------------------------
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
------------------------------
[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]
------------------------------
[1. 1. 1. 1.]
------------------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
------------------------------
[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]


### 4 full array

In [23]:
ar2 = np.full((15),5)
print(ar2)
print('-'*30)
arr2 =np.full((5,3),2)
print(arr2)
print('-'*30)


[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
------------------------------
[[2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]]
------------------------------


### 5 eyes array

In [24]:
arr= np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
arr2 = np.eye(4)
print(arr2)
print('-'*30)
arr1 = np.eye(5)
print(arr1)
print('-'*30)
print(np.rot90(arr1))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
------------------------------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
------------------------------
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


### Identity and Diagonal Array

In [26]:
print(np.identity(5))
print('-'*30)
print(np.diag(np.identity(5)))
print('-'*30)
print(np.diag(np.identity(3)))
print('-'*30)
print(np.diag(np.arange(3,8)))
print(np.diag(np.diag(np.arange(3,7))))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
------------------------------
[1. 1. 1. 1. 1.]
------------------------------
[1. 1. 1.]
------------------------------
[[3 0 0 0 0]
 [0 4 0 0 0]
 [0 0 5 0 0]
 [0 0 0 6 0]
 [0 0 0 0 7]]
[3 4 5 6]


## Numpy Random Numbers
* The np.random.rand method, generates an array with random numbers that are uniformly distributed between 0 and 1.

* The np.random.randn method, generates an array with random numbers that are normally distributed with mean = 0 and sd = 1.

* The np.random.randint method, generates an array with random numbers that are uniformly distributed between 0 and given integer.

* The np.random.uniform method, generates random float values.

In [27]:
df=np.random.seed(222)
print(df)

df1 = np.random.rand(3,3) # uniformly distribute value 
print(df1)
print('-'*30)
df2 = np.random.randn(3,3) #normaly distribute value 
print(df2)
print('-'*30)
x = np.random.randn(1,3)
print(np.round(np.mean(x)),np.round(np.std(x)))
print('-'*30)
df3 = np.random.randint(10,50, size = (3,4))
print(df3)
print('-'*40)
df5 = np.random.randint(40,60,size = (4,6))
print(df5)
df4 = np.random.uniform(10,50,size =(0,0))

None
[[0.52602843 0.68531719 0.83567419]
 [0.65376526 0.03702195 0.18015566]
 [0.76056942 0.22430462 0.73513507]]
------------------------------
[[ 1.00333914 -0.91596844  0.10388737]
 [ 1.50120804 -0.20745062  0.82179006]
 [-0.14253236 -0.79882014 -0.83804721]]
------------------------------
-0.0 1.0
------------------------------
[[37 14 19 15]
 [25 30 14 34]
 [39 39 14 42]]
----------------------------------------
[[56 57 51 59 47 57]
 [50 42 53 44 42 44]
 [42 59 46 42 56 47]
 [59 55 58 40 54 54]]


### Array Indexing

In [28]:
arr2 = np.arange(50,100)
print(arr2)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]


In [29]:
print(arr2[0])
print(arr2[-1])
print(arr2[9])
print(arr2[-15])
print(arr2[[9,19,29,39,49]])
print(arr2[range(9,50,10)])

50
99
59
85
[59 69 79 89 99]
[59 69 79 89 99]


In [30]:
arr3 = arr2.reshape(5,10)
print(arr3)

[[50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [31]:
print(arr3[0])
print(arr3[-1])
print(arr3[2,4])
print(arr3[3,1])
print(arr3[2,7])

[50 51 52 53 54 55 56 57 58 59]
[90 91 92 93 94 95 96 97 98 99]
74
81
77


In [32]:
arr4 = arr2.reshape(5,5,2)

In [33]:
print(arr4)

[[[50 51]
  [52 53]
  [54 55]
  [56 57]
  [58 59]]

 [[60 61]
  [62 63]
  [64 65]
  [66 67]
  [68 69]]

 [[70 71]
  [72 73]
  [74 75]
  [76 77]
  [78 79]]

 [[80 81]
  [82 83]
  [84 85]
  [86 87]
  [88 89]]

 [[90 91]
  [92 93]
  [94 95]
  [96 97]
  [98 99]]]


In [34]:
print(arr4[0])
print(arr4[3,3,1])
print(arr4[3][3][1])
print(arr4[4][3])

[[50 51]
 [52 53]
 [54 55]
 [56 57]
 [58 59]]
87
87
[96 97]


In [35]:
print(arr2)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]


In [36]:
print(arr2[range(0,10)])
print(arr2[2:6])
print(arr2[0:10][2:6])

[50 51 52 53 54 55 56 57 58 59]
[52 53 54 55]
[52 53 54 55]


In [37]:
print(arr3)

[[50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [38]:
print(arr3[2:6])

[[70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [39]:
print(arr3[2:5,:])
print(arr3[1:4,1:4])
print(arr3[2:5,5:])

[[70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[61 62 63]
 [71 72 73]
 [81 82 83]]
[[75 76 77 78 79]
 [85 86 87 88 89]
 [95 96 97 98 99]]


In [40]:
print(np.transpose(arr3))

[[50 60 70 80 90]
 [51 61 71 81 91]
 [52 62 72 82 92]
 [53 63 73 83 93]
 [54 64 74 84 94]
 [55 65 75 85 95]
 [56 66 76 86 96]
 [57 67 77 87 97]
 [58 68 78 88 98]
 [59 69 79 89 99]]


In [41]:
np.fliplr(arr3)

array([[59, 58, 57, 56, 55, 54, 53, 52, 51, 50],
       [69, 68, 67, 66, 65, 64, 63, 62, 61, 60],
       [79, 78, 77, 76, 75, 74, 73, 72, 71, 70],
       [89, 88, 87, 86, 85, 84, 83, 82, 81, 80],
       [99, 98, 97, 96, 95, 94, 93, 92, 91, 90]])

In [42]:
np.flipud(arr3)

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [43]:
np.flip(arr3 ,axis=1)

array([[59, 58, 57, 56, 55, 54, 53, 52, 51, 50],
       [69, 68, 67, 66, 65, 64, 63, 62, 61, 60],
       [79, 78, 77, 76, 75, 74, 73, 72, 71, 70],
       [89, 88, 87, 86, 85, 84, 83, 82, 81, 80],
       [99, 98, 97, 96, 95, 94, 93, 92, 91, 90]])

In [44]:
np.flip(arr3,axis=0)

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

### Statistical functions

In [52]:
print(np.mean(arr3))
print(np.median(arr3))
print(np.var(arr3)) # var = variance
print(np.std(arr3)) #std = str Dev
print(np.sum(arr3))
print(np.min(arr3))
print(np.max(arr3))

74.5
74.5
208.25
14.430869689661812
3725
50
99


In [54]:
np.median(np.array(range(8)))
np.median(np.array(range(7)))

3.5

3.0

### Stacking of arrays

* Vertical stacking(row wise) using vstack()
* Horizontal stacking(column wise) using hstack()
* Depth wise stacking(along third axis) using dstack()

In [67]:
a = np.arange(1,13).reshape(3,4)
b = np.arange(1,9).reshape(2,4)
c = np.arange(1,7).reshape(3,2)

In [68]:
print(a,b,c,sep = '\n\n')

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[1 2 3 4]
 [5 6 7 8]]

[[1 2]
 [3 4]
 [5 6]]


In [69]:
np.hstack((a,c))

array([[ 1,  2,  3,  4,  1,  2],
       [ 5,  6,  7,  8,  3,  4],
       [ 9, 10, 11, 12,  5,  6]])

In [70]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [73]:
d = np.ones((3,4))
print(d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [75]:
np.dstack((a,d))

array([[[ 1.,  1.],
        [ 2.,  1.],
        [ 3.,  1.],
        [ 4.,  1.]],

       [[ 5.,  1.],
        [ 6.,  1.],
        [ 7.,  1.],
        [ 8.,  1.]],

       [[ 9.,  1.],
        [10.,  1.],
        [11.,  1.],
        [12.,  1.]]])

### Splitting of arrays

In [76]:
arr2 = np.arange(1,25).reshape(4,6)

In [77]:
print(arr2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [82]:
np.hsplit(arr2,3)

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22]]),
 array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24]])]

In [83]:
np.hsplit(arr2,2)

[array([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15],
        [19, 20, 21]]),
 array([[ 4,  5,  6],
        [10, 11, 12],
        [16, 17, 18],
        [22, 23, 24]])]

In [84]:
np.vsplit(arr2,2)

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])]

In [86]:
np.vsplit(arr2,4)

[array([[1, 2, 3, 4, 5, 6]]),
 array([[ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18]]),
 array([[19, 20, 21, 22, 23, 24]])]

### append() & concatenate()

In [89]:
np.concatenate((a,c),axis = 1)
np.concatenate((a,b),axis = 0)

array([[ 1,  2,  3,  4,  1,  2],
       [ 5,  6,  7,  8,  3,  4],
       [ 9, 10, 11, 12,  5,  6]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

### Updating an array with where()

In [93]:
a = np.arange(50,80).reshape(5,6)
b = np.arange(60,90).reshape(5,6)

In [94]:
print(a,b, sep = '\n\n')

[[50 51 52 53 54 55]
 [56 57 58 59 60 61]
 [62 63 64 65 66 67]
 [68 69 70 71 72 73]
 [74 75 76 77 78 79]]

[[60 61 62 63 64 65]
 [66 67 68 69 70 71]
 [72 73 74 75 76 77]
 [78 79 80 81 82 83]
 [84 85 86 87 88 89]]


In [97]:
np.where(a%2==0,1,0)
np.sum(np.where(a%2==0,1,0))

array([[1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0]])

15

In [98]:
np.where(a>56,True,False)

array([[False, False, False, False, False, False],
       [False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [99]:
np.union1d(a,b)

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89])

In [100]:
np.intersect1d(a,b)

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
       77, 78, 79])

In [101]:
np.setdiff1d(a,b)

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [102]:
np.setdiff1d(b,a)

array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89])

In [107]:
np.random.seed(555)
arr1 = np.random.uniform(10,20,(3,4))
print(arr1)

[[17.17834087 10.47855133 19.44471978 16.8638004 ]
 [15.81207334 11.42678616 19.45919181 13.39990587]
 [16.20435458 14.52959644 12.3976742  10.34504591]]


In [108]:
arr1.astype(int)

array([[17, 10, 19, 16],
       [15, 11, 19, 13],
       [16, 14, 12, 10]])

In [109]:
arr1.astype(str)

array([['17.178340874802497', '10.478551325561956', '19.44471977593777',
        '16.863800396919427'],
       ['15.812073341927952', '11.426786160283044', '19.45919180957477',
        '13.399905866287362'],
       ['16.2043545816585', '14.529596444285833', '12.397674196008914',
        '10.345045909201573']], dtype='<U32')

### Array Broadcasting
> Broadcasting allows binary operations to be performed on arrays of different sizes.

In [110]:
np.arange(3)

array([0, 1, 2])

In [112]:
np.arange(3)+5

array([5, 6, 7])

In [114]:
np.ones((3,3)) +np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])